composer:
	composer install

database:
	php bin/console doctrine:database:create

migration:
	php bin/console make:migration

migrate:
	php bin/console doctrine:migrations:migrate

fixture:
	php bin/console hautelook:fixtures:load
