steps:
  - id: 'migrate'
    name: 'gcr.io/google-appengine/exec-wrapper'
    args: ['-i', '${_IMAGE}',
           '-s', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
           '-e', 'PROJECT_ID=${PROJECT_ID}',
           '-e', 'DATABASE_URL=${_DATABASE_URL}',
           '-e', 'APP_ENV=dev',
           '--', 'php', 'bin/console', 'doctrine:migrations:migrate', '-n']
  - id: 'fixture'
    name: 'gcr.io/google-appengine/exec-wrapper'
    args: ['-i', '${_IMAGE}',
           '-s', '${PROJECT_ID}:${_REGION}:${_INSTANCE_NAME}',
           '-e', 'PROJECT_ID=${PROJECT_ID}',
           '-e', 'DATABASE_URL=${_DATABASE_URL}',
           '-e', 'APP_ENV=dev',
           '--', 'php', 'bin/console', 'hautelook:fixtures:load', '-n', '--purge-with-truncate']
